name: Scala Dev Deploy

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2

    - name: Deploy to production
      env: # Set Oracle credentials secret as an input
        credentials: ${{ secrets.ORACLE_CREDENTIALS_DEV }}
        branch_name: ${{ steps.branch-name.outputs.current_branch }}
      run: |
        echo "$credentials" >> ssh-key.key
        chmod 400 ssh-key.key
        ssh -o StrictHostKeyChecking=no -i ssh-key.key ubuntu@144.21.49.17 << EOF
        sudo su -
        ./runUpdate "$branch_name" || (echo "Retry..." && ./runUpdate "$branch_name")
        EOF
